### ISSUE TITLE
morphMap Issue

### ISSUE THREAD

**Issue by sineld** [michaelbaril/sqlout#1]
Using,

```
        Relation::morphMap([
            'App\Models\Profile',
            'App\Models\User',
        ]);
```
in **AppServiceProvider** breaks application. I'm not sure if it is related to your package.
Please check.

**Comment by michaelbaril** [comment]
Hi,
I would need more information to understand the context. Could you provide me with the error message and stack trace?
Thanks

**Comment by sineld** [comment]
Let me explain, when using Polymorhic relations, Laravel writes the whole Model with the namespace (**App\User**), but when we add the morphMap to AppServiceProvider like below:

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Database\Eloquent\Relations\Relation;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        Relation::morphMap([
            'App\User',
        ]);
    }
}

```
**App\User** becomes **users** and this occurs error below:

```
/Users/sineld/Code/laravel58/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
    public function getMorphClass()
    {
        $morphMap = Relation::morphMap();
 
        if (! empty($morphMap) && in_array(static::class, $morphMap)) {
            return array_search(static::class, $morphMap, true);
        }
 
        return static::class;
    }
 
    /**
     * Create a new model instance for a related model.
     *
     * @param  string  $class
     * @return mixed
     */
    protected function newRelatedInstance($class)
    {
        return tap(new $class, function ($instance) {
            if (! $instance->getConnectionName()) {
                $instance->setConnection($this->connection);
            }
        });
    }
 
    /**
     * Get all the loaded relations for the instance.
     *
     * @return array
     */
    public function getRelations()
    {
        return $this->relations;
    }
 
    /**
     * Get a specified relationship.
     *
     * @param  string  $relation
Arguments
"Class 'users' not found"
```

Please see images attached.
![2019-10-03 22-27-28 (MySQL 5 7 27) localhost homestead searchindex (2)](https://user-images.githubusercontent.com/445349/66158528-bc16b680-e62e-11e9-8f11-c255747bda41.jpg)
![2019-10-03 22-37-03 Whoops! There was an error](https://user-images.githubusercontent.com/445349/66158555-c46ef180-e62e-11e9-9a1c-b5c58ec24bf6.jpg)

**Comment by michaelbaril** [comment]
Indeed, it's a bug. It should be fixed with the latest commit on `master`, please check.

**Comment by sineld** [comment]
Yes, it's solved. Thanks. You may close the issue.

**Comment by michaelbaril** [comment]
Thanks for your feedback. I've included the fix in the latest release.
